export const topics = [
    { name: "🏡 홈", link: "/home" },
    { name: "👨‍🏫 교육", link: "/edu" },
    { name: "🎫 자격증", link: "/certificate" },
    { name: "🖥️ IT", link: "/it" },
    { name: "🏋️ 건강", link: "/health" },
    { name: "🏥 병원", link: "/hospital" },
    { name: "🎲 게임", link: "/game" },
    { name: "🦋 뷰티", link: "/beauty" },
    { name: "💰 금융", link: "/finance" },
    { name: "🏬 보험", link: "/insurance" },
    { name: "👔 경영/창업", link: "/business" },
    { name: "🚗 자동차", link: "/car" },
    { name: "🛒 쇼핑", link: "/shopping" },
    { name: "🏠 리빙", link: "/living" },
    { name: "🎙️ 엔터테인먼트", link: "/entertainment" },
    { name: "🌍 사회", link: "/social" },
    { name: "🦠 기타", link: "/others" },
];
